name: kurdistan_visitor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # firebase_core : ^0.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  # firebase_auth: ^0.20.1
  firebase_core: ^1.11.0
  # firebase_core: ^1.6.0
  # firebase_core: ^0.7.0
  cloud_firestore: ^2.5.1
  # cloud_firestore: ^0.16.0+1
  firebase_database: ^8.0.0
  firebase_storage: ^10.0.3
  # package for file selected best package
  file_picker: ^4.0.3
  # file_picker: ^3.0.1
  # file_picker: ^2.1.7
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  custom_navigator: ^0.3.0
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0
  # this package use for not singout after go out app or restart
  shared_preferences: ^2.0.8
  http: ^0.13.4

  # email_validator: ^1.0.0
  email_validator: ^2.0.1
  data_connection_checker: ^0.3.4
  
  carousel_slider: ^4.0.0
  # carousel_pro: ^1.0.0
  
  # using this package for dot slider with some affection
  smooth_page_indicator: ^1.0.0+2

  # using this package for check wifi and mobile_data and ethical. networks 
  connectivity_plus: ^1.1.0
  # start   those  packages below using for internet connection continusly 
  internet_connection_checker: ^0.0.1+2
  overlay_support: ^1.2.1
  path_provider: ^2.0.7
  # end
  # connectivity: ^3.0.6
  # carousel_slider: ^4.0.0

dev_dependencies:
  flutter_native_splash: ^1.3.1
 
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/mount.png
  android: true
  ios: true




flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/isomatric/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
